version: '3.5'

services:
  server:
    container_name: server
    build: .
    command: npm run start:dev
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:15.0
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
